#ARQUIVO CSV
# import csv
# dados=[
#     ["Marta","marta@cbf.com"],
#     ["Pele","peleeterno@god.ce"],
#     ["Ronaldo","fenomeno@cbf.com"]
# ]

# with open('contacts.csv','w',newline='') as arquivo:
#     escrever=csv.writer(arquivo)
#     for linha in dados:
#         escrever.writerow(linha)




        
#Este código irá abrir o arquivo, ler cada linha e, 
#em seguida, imprimir cada linha para o console.
# import csv
# with open('contacts.csv','r') as arquivo:
#     lendo=csv.reader(arquivo)
#     for linha in lendo:
#         print (linha[0:1])